/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package millionwinner;


public class category extends javax.swing.JFrame {

    static category categoryFrame;

    /**
     * Creates new form category
     */
    public category() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        mathQuizBtn = new javax.swing.JButton();
        javaQuizBtn = new javax.swing.JButton();
        pythonQuizBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(194, 217, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(194, 217, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        mathQuizBtn.setBackground(new java.awt.Color(119, 82, 254));
        mathQuizBtn.setFont(new java.awt.Font("Showcard Gothic", 0, 16)); // NOI18N
        mathQuizBtn.setForeground(new java.awt.Color(0, 0, 0));
        mathQuizBtn.setText("math");
        mathQuizBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mathQuizBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mathQuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathQuizBtnActionPerformed(evt);
            }
        });

        javaQuizBtn.setBackground(new java.awt.Color(119, 82, 254));
        javaQuizBtn.setFont(new java.awt.Font("Showcard Gothic", 0, 16)); // NOI18N
        javaQuizBtn.setForeground(new java.awt.Color(0, 0, 0));
        javaQuizBtn.setText("java");
        javaQuizBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        javaQuizBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        javaQuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaQuizBtnActionPerformed(evt);
            }
        });

        pythonQuizBtn.setBackground(new java.awt.Color(119, 82, 254));
        pythonQuizBtn.setFont(new java.awt.Font("Showcard Gothic", 0, 16)); // NOI18N
        pythonQuizBtn.setForeground(new java.awt.Color(0, 0, 0));
        pythonQuizBtn.setText("paython");
        pythonQuizBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pythonQuizBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pythonQuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pythonQuizBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("choose the category");

        jButton4.setBackground(new java.awt.Color(119, 82, 254));
        jButton4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("home");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pythonQuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(javaQuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(mathQuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(mathQuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(javaQuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pythonQuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mathQuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathQuizBtnActionPerformed
            quiz quizFrame = new quiz("math");
            quizFrame.setVisible(true);
            quizFrame.pack();
            quizFrame.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_mathQuizBtnActionPerformed

    private void javaQuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaQuizBtnActionPerformed
            quiz quizFrame = new quiz("java");
            quizFrame.setVisible(true);
            quizFrame.pack();
            quizFrame.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_javaQuizBtnActionPerformed

    private void pythonQuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pythonQuizBtnActionPerformed
            quiz quizFrame = new quiz("python");
            quizFrame.setVisible(true);
            quizFrame.pack();
            quizFrame.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_pythonQuizBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Home HomeFrame = new Home();
        HomeFrame.setVisible(true);
        HomeFrame.pack();
        HomeFrame.setLocationRelativeTo(null);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton javaQuizBtn;
    private javax.swing.JButton mathQuizBtn;
    private javax.swing.JButton pythonQuizBtn;
    // End of variables declaration//GEN-END:variables
}
